# Generated by Django 3.2.3 on 2021-05-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratearticle',
            name='user',
        ),
        migrations.RemoveField(
            model_name='article',
            name='rating',
        ),
        migrations.AddField(
            model_name='article',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='rate'),
        ),
    ]
