# Generated by Django 3.2.3 on 2021-05-28 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210528_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(max_length=2000, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Цитата'),
        ),
    ]
